<?php
// i18n-map.php @generated by automattic/jetpack-composer-plugin
return array(
  'domain' => 'jetpack-search',
  'type' => 'plugins',
  'packages' => array(
    'jetpack-admin-ui' => array(
      'path' => 'jetpack_vendor/automattic/jetpack-admin-ui',
      'ver' => '0.8.2',
    ),
    'jetpack-assets' => array(
      'path' => 'jetpack_vendor/automattic/jetpack-assets',
      'ver' => '4.3.34',
    ),
    'jetpack-boost-core' => array(
      'path' => 'jetpack_vendor/automattic/jetpack-boost-core',
      'ver' => '0.4.4',
    ),
    'jetpack-boost-speed-score' => array(
      'path' => 'jetpack_vendor/automattic/jetpack-boost-speed-score',
      'ver' => '0.4.14',
    ),
    'jetpack-config' => array(
      'path' => 'jetpack_vendor/automattic/jetpack-config',
      'ver' => '3.1.2',
    ),
    'jetpack-connection' => array(
      'path' => 'jetpack_vendor/automattic/jetpack-connection',
      'ver' => '8.3.3',
    ),
    'jetpack-explat' => array(
      'path' => 'jetpack_vendor/automattic/jetpack-explat',
      'ver' => '0.4.22',
    ),
    'jetpack-ip' => array(
      'path' => 'jetpack_vendor/automattic/jetpack-ip',
      'ver' => '0.4.11',
    ),
    'jetpack-jitm' => array(
      'path' => 'jetpack_vendor/automattic/jetpack-jitm',
      'ver' => '4.3.32',
    ),
    'jetpack-licensing' => array(
      'path' => 'jetpack_vendor/automattic/jetpack-licensing',
      'ver' => '3.1.6',
    ),
    'jetpack-my-jetpack' => array(
      'path' => 'jetpack_vendor/automattic/jetpack-my-jetpack',
      'ver' => '5.36.1-alpha1778082656',
    ),
    'jetpack-password-checker' => array(
      'path' => 'jetpack_vendor/automattic/jetpack-password-checker',
      'ver' => '0.4.10',
    ),
    'jetpack-plugins-installer' => array(
      'path' => 'jetpack_vendor/automattic/jetpack-plugins-installer',
      'ver' => '0.5.8',
    ),
    'jetpack-protect-models' => array(
      'path' => 'jetpack_vendor/automattic/jetpack-protect-models',
      'ver' => '0.6.2',
    ),
    'jetpack-protect-status' => array(
      'path' => 'jetpack_vendor/automattic/jetpack-protect-status',
      'ver' => '0.7.9',
    ),
    'jetpack-search-pkg' => array(
      'path' => 'jetpack_vendor/automattic/jetpack-search',
      'ver' => '0.59.0-alpha1778082656',
    ),
    'jetpack-stats' => array(
      'path' => 'jetpack_vendor/automattic/jetpack-stats',
      'ver' => '0.19.0',
    ),
    'jetpack-sync' => array(
      'path' => 'jetpack_vendor/automattic/jetpack-sync',
      'ver' => '4.37.0',
    ),
    'jetpack-wp-abilities' => array(
      'path' => 'jetpack_vendor/automattic/jetpack-wp-abilities',
      'ver' => '0.1.0',
    ),
  ),
);
